config/routes.rb
Rails.application.routes.draw do

  root  "jobs#index"
  
  resources :boats
  
  get "/signin" => "sessions#new"
  post "/signin" => "users#signin"
  post "/logout" => "sessions#destroy"
  
  resources :users
  
  resources :jobs
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
	has_attached_file :image, styles: { large: "600x660>", medium: "300x300>", thumb: "100x100#" } 
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :jobs
	has_many :users, :through => :jobs
	validates :name, uniqueness: true
	validates :name, :containers, :location, presence: true

end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :boat
	belongs_to :user
	validates :title, uniqueness: true
	validates :title, :info, :origin, :destination, :cost, :containers, :boat_id, :user_id, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :jobs
	has_many :boats, :through => :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  	def current_user
      if session[:user_id]
    current_user = User.find(session[:user_id])
    end
  end

      helper_method :current_user, :logged_in?

    def logged_in?
  		current_user != nil
  	end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
      if @boat.save
        flash[:notice] = "Boat created successfully."
        redirect_to "/boats"
      else
        render "/boats/new"
      end
  end

  def show
      @boat = Boat.find(params[:id])
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    if @boat.update(boat_params)
      flash[:notice] = "Boat updated successfully."
      redirect_to "/boats"
    else
      render "/boats/#{:id}"
    end
  end

  def destroy
    boat = Boat.find(params[:id])
    boat.destroy
    flash[:notice] = "Boat was deleted successfully."
    redirect_to "/boats/"
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :containers, :location, :image)
end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@jobs = Job.all
	end

	def show
		@job = Job.find(params[:id])
		@boat = Boat.find(@job.boat_id)
		@user = User.find(@job.user_id)
	end

	def new
		@boats = Boat.all.map{ |boat| [ boat.name, boat.id ] }
		@job = Job.new
	end

	def create
		@job = Job.new(job_params)
		@job.user_id = current_user.id
		@job.boat_id = params[:boat_id]
		if @job.save!
			redirect_to "/jobs/"
		else
			render "/jobs/new"
		end
	end

	def destroy
		job = Job.find(params[:id])
		job.destroy
		flash[:message] = "job deleted"
		redirect_to "/jobs/"
	end

	def edit
		@boats = Boat.all.map{ |boat| [ boat.name, boat.id ] }
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.user_id = current_user.id
		job_params[:boat_id] = params[:boat_id]
		@job.boat_id = params[:boat_id]
		if @job.update!(job_params)
			@job.boat_id = params[:boat_id]
			redirect_to "/jobs/"
		else
			render edit_job_path
		end
	end

	private
	def job_params
		params.require(:job).permit(:title,:info, :origin, :destination, :cost, :containers, :boat_id, :user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

    end

  	def destroy
  		session[:user_id] = nil
  		redirect_to '/'
  	end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end


  def create
  	user = User.new(user_params)
  	if user.save
  		redirect_to "/"
  	else
  		render "/users/new"
  	end
  end

  def signin
    @user = User.find_by_name(params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/users"
    else
      redirect_to :controller => 'sessions', :action => 'new'
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if(user.update(user_params))
      redirect_to "/"
    else
      render edit_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
      redirect_to "/"
  end





  private
	 def user_params
	  params.require(:user).permit(:name, :password)
	 end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boats/edit.html.erb
<div class="boatEdit">
<h1>Edit Boat</h1>
<p>Complete the following: </p>

<%= form_for @boat do |f| %>
<p>Name: <%= f.text_field :name %></p>
<p>Containers: <%= f.text_field :containers %></p>
<p>Location: <%= f.text_field :location %></p>
<%=f.file_field :image %>
<p><%= f.submit "Edit" %></p>
<% end %>
</div>

app/views/boats/index.html.erb
<% if !flash[:notice].blank? %>
<div class="boatNotice">
  <%= flash[:notice] %>
</div>
<% end %>

<div class="boatIndex">
<h1>List of Boats</h1>
<p>Scroll through the options</p>

<%= link_to "New Boat", new_boat_path %>
<br>
<br>


<div class="boat-container">
<% @boats.each do |b| %>
<div class="boat-childeren">
<div class="boatName"><h1><a href="/boats/<%= b.id %>" target="_blank"><%= b.name %></a></h1></div>
 <div class="boat-images"><% if b.image.file? %>
<%= image_tag b.image.url(:medium) %>
<% else %>
<%= image_tag 'boatlogo.png', alt: '' %>
<% end %>
</div>
<hr>
<strong>Info:</strong>
<div><%= b.containers %> containers</div>
<div><%= b.location %></div>
<br>
</div>
<% end %>
</div>
</div>

app/views/boats/new.html.erb
<div class="boatNew">
<h1>Create a New Boat</h1>
<p>Complete the following: </p>

<%= form_for @boat, hmtl: { multipart: true } do |f| %>
<p>Name: <%= f.text_field :name %></p>
<p>Containers: <%= f.text_field :containers %></p>
<p>Location: <%= f.text_field :location %></p>
<%=f.file_field :image %>
<p><%= f.submit %></p>
<% end %>
</div>

app/views/boats/show.html.erb
<% if !flash[:notice].blank? %>
<div class="boatNotice">
  <%= flash[:notice] %>
</div>
<% end %>

<div class=boatShow>
<h1>Boats</h1>




<div id="boats-showpage" >

<div class="boatImage">
<% if @boat.image.file? %>
  <%= image_tag @boat.image.url(:large) %>
  <% else %>
  <%= image_tag 'boatlogo.png', alt: '' %>
  <% end %>
</div>
<div class="boatName">
  <h4>Boat Name:</h4>
  <p><%= @boat.name%></p>
</div>
<div class="boatName">
    <h4>Containers:</h4>
     <p><%= @boat.containers%></p>
</div>
<div class="boatName">
  <h4>Boat Location:</h4>
  <p><%= @boat.location%></p>
</div>
</div>

<%= link_to "Edit", edit_boat_path %>
|
<%= link_to "Delete", boat_path, method: :delete %>
</div>

app/views/jobs/edit.html.erb
<h2>Edit "<%= @job.title %>"</h2>
<%= form_for @job do |f| %>
	<b>name</b>
	<%= f.text_field :title %><br>
	<b>about this job</b>
	<%= f.text_field :info %>
	<p>
	<b>select boat</b>
	<%= select_tag(:boat_id, options_from_collection_for_select(Boat.all, :id, :name), include_blank: "Select Boat") %>
	<br>
	<b>number of shipping containers needed</b>
	<%= f.number_field :containers %><br>
	<b>going from</b>
	<%= f.text_field :origin %>
	<b> to </b>
	<%= f.text_field :destination %><br>
	<b>total job price</b>
	<%= f.number_field :cost %>
	<%= hidden_field_tag :user_id, current_user.id %>
	<br><%= f.submit "update" %>
<% end %>

app/views/jobs/index.html.erb
<h2>All jobs on record</h2>
<div id="jobswrapper">
	<% @jobs.each do |job| %>
		<div class="jobbox">
			<h3><%= job.title %></h3>
			<i><b>from</b> <%= job.origin %> <b>to</b> <%= job.destination %></i>
			<div class="jobdets">
				<% if Boat.find(job.boat_id).image.file? %>
					<%= image_tag Boat.find(job.boat_id).image.url(:medium) %>
				<% else %>
					<%= image_tag 'boatlogo.png', alt: '' %>
				<%end %>
				<%= job.info %>
				<a href="/jobs/<%= job.id %>">more info</a>
			</div>
		</div>
	<% end %>
</div>

app/views/jobs/new.html.erb
<h2>Create a new job</h2>
<%= form_for @job do |f| %>
	<b>name of the new job</b>
	<%= f.text_field :title %><br>
	<b>about this job</b>
	<%= f.text_field :info %>
	<p>
	<b>select boat</b>
	<%= select_tag(:boat_id, options_from_collection_for_select(Boat.all, :id, :name), include_blank: "Select Boat") %>
	<br>
	<b>number of shipping containers needed</b>
	<%= f.number_field :containers %><br>
	<b>going from</b>
	<%= f.text_field :origin %>
	<b> to </b>
	<%= f.text_field :destination %><br>
	<b>total job price</b>
	<%= f.number_field :cost %>
	<%= hidden_field_tag :user_id, current_user.id %>
	<br>
	<%= f.submit "create" %>
<% end %>

app/views/jobs/show.html.erb
<div id="jobwrapper">
	<h2><%= @job.title %></h2>
	<div class="sjobuser">
	ordered by <a href="/users/<%= @user.id %>"><%= @user.name %></a>
	</div>
	<div class="sjobtravel">
	<%= @job.containers %> containers, <%= @job.origin %> to <%= @job.destination %>
	</div>
	<div class="sjobfeatures">
		total price: $<%= @job.cost %>
	</div>
	<div class="sjobdets">
		<div class="sjobinfo">
			<%= @job.info %>
		</div>
		<div class="sjobactions">
				<a href="/jobs/<%= @job.id %>/edit" style="margin: 0 35px 0 15px;">edit job</a>
				<%= link_to "delete this job", job_path, method: :delete %>
		</div>
	</div>
	<div class="sjobboat">
	assigned to <a href="/boats/<%= @boat.id %>"><%= @boat.name %></a>
	</div>
	<div class="sjobpic">
		<% if @boat.image.file? %>
			<%= image_tag @boat.image.url(:medium) %>
		<% else %>
			<%= image_tag 'boatlogo.png', alt: '' %>
		<%end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShippedProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div class="logoTitle"><h2>bulwark Listings</h2></div>
  <div class="topParts"><h2>  . . . . .You can rely on us</h2></div>
<nav>
  <li><a href='/'>Home</a></li>

  <% if !logged_in? %>
        <li><a href='/users/new'>Sign Up</a></li>
         <li><a href='/signin'>Sign In</a></li>
        <% else %>
        <li class="userTag">Current User: <%= current_user.name %></li>
        <li><%= link_to "Edit User", edit_user_path(:id => current_user.id) %></li>
        <li><%= link_to "Log out", logout_path, :method => "sessions#destroy" %></li>

      <% end %>
      <div class="dropdown">
        <li class="btn"><a href='/'>Other links</a></li>
            <div class="dropdown-content">
              <a href ="/boats">Show Boats</a>
              <a href ="/boats/new">New Boat</a>
              <a href ="/users">Show Users</a>
              <a href ="/users/new">Create a User</a>
              <a href ="/jobs">Show Jobs</a>
            <% if logged_in? %>
              <a href ="/jobs/new">Post New Job</a>
            <% end %>
            </div>
      </div>
</nav>


  <% if !flash[:notice].blank? %>
  <div class="boatNotice">
    <%= flash[:notice] %>
  </div>
  <% end %>

    <div id="mainall"><%= yield %></div>
    <footer>
      <p id="copywrite">Copyright (c) 2018 Copyright Holder All Rights Reserved.</p>
    </footer>
  </body>

</html>

app/views/users/edit.html.erb
<h2>Edit User:</h2>
<div class='create-edit'>
	<%= form_for @user do |f| %>
</p>Edit Name: <%= f.text_field :name %></p>
</p>	Edit Passsword: <%= f.text_field :password %></p>
	<%= f.submit "update user" %>

	<% end %>
</div>
<%= link_to "Delete User", user_path,
							method: :delete,
							data: {confirm: 'are you sure?'} %>

app/views/users/index.html.erb
<h2>Users Index:</h2>
<div class='users-list'>
	<% @users.each do |user| %>
		<div><%= user.name %></a></div>
	<% end %>
</div>

app/views/users/new.html.erb
<h2>Sign Up:</h2>
<div class='create-edit'>
	<%= form_for @user do |f| %>
	<p> Name: <%= f.text_field :name %> </p>

	<p> Password: <%= f.text_field :password %> </p>
	<%= f.submit %>

	<% end %>
</div>